version: "3.7"

services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:alpine

  redis-queue:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      REDIS_CACHE: redis://redis-cache:6379
      REDIS_QUEUE: redis://redis-queue:6379
    ports:
      - "8001:8000"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      bash -c "
      bench init frappe-bench &&
      cd frappe-bench &&
      bench new-site site1.local
        --db-root-password=123
        --admin-password=admin &&
      bench get-app erpnext &&
      bench --site site1.local install-app erpnext &&
      bench start
      "

volumes:
  mariadb-data: